### ISSUE TITLE
too many critical errors in server and client don't have error descriptions presented to the user

### ISSUE THREAD

**Issue by paulcallen** [Microsoft/omi#218]
For instance, wsman client for wide char support, for server when a provider cannot be found or loaded.

**Comment by JumpingYang001** [comment]
Fix the provider issue on #283, thanks.

**Comment by JumpingYang001** [comment]
For wide char support, since we "Deprecate wchar builds for regress and configure" in https://github.com/Microsoft/omi/commit/62d2fb651eb8a2a1bbc50cbc598525700f65ee7f , I am not sure if we still need to fix wsman client for wide char support when do operations on instance, could you help to confirm this?
I will fix it if it is needed, thanks.

**Comment by palladia** [comment]
We are removing wchar support.  Still need this?
