### ISSUE TITLE
Can't run install builder from OMI (?)

### ISSUE THREAD

**Issue by andschwa** [Microsoft/omi#27]
I need to make packages for OMI per our internal project, and while the install builder setup is available within OMI, as far as I and @jeffaco can tell, the OMI packages can't be built from OMI itself.

@johnkord are we mistaken here, or do we need to get the `installbuilder` scripts made available in OMI (or a separate repo)?

**Comment by paulcallen** [comment]
going to close this until we decide to resurrect this discussion.

**Comment by jeffaco** [comment]
I didn't realize that there was an issue for this. I completed this work some time ago, but because I didn't realize there was an issue for it, I didn't close the issue:

```
jeffcof:omi> git --no-pager show --stat ed5607e
commit ed5607e
Author: Jeff Coffler <jeff@taltos.com>
Date:   Mon Nov 14 11:55:24 2016

    Add --enable-microsoft to configure, enable native installation kits

 Unix/build.mak                  |  87 +--------------
 Unix/configure                  | 228 ++++++++++++++++++++++++++++++----------
 Unix/installbuilder/GNUmakefile |   2 +-
 3 files changed, 179 insertions(+), 138 deletions(-)
```

These changes, assuming you're using the [Build-omi](https://github.com/Microsoft/Build-omi/) superproject, will automatically build a package. These packages are used in dependent packages (like SCXcore, SCXcm, etc).
