### ISSUE TITLE
Agent reports incorrect amount of Free Disk Space 

### ISSUE THREAD

**Issue by yoanisgil** [Microsoft/omi#271]
I've been told to report this issue here (https://github.com/Microsoft/OMS-Agent-for-Linux/issues/430)

Hi, 

We're considering using  OMS Agent for Linux to monitor our containers running on top of a K8s cluster and we've noticed that there is a significant discrepancy between the amount of reported free space and the actual free space. See images for below. 

Also note the the percentage of used space is correct.

Maybe I'm missing something obvious, which is why I'm just posting here.

OMI Agent version
```
root@omsagent-mmwn4:/opt# /opt/omi/bin/omiagent --version
/opt/omi/bin/omiagent: OMI-1.2.0-13 - Wed Mar 29 16:26:22 PDT 2017
```

OMI Server version
```
root@omsagent-mmwn4:/opt# /opt/omi/bin/omiserver -v
/opt/omi/bin/omiserver: OMI-1.2.0-13 - Wed Mar 29 16:26:22 PDT 2017
```

Actual Free Space
=============
![capture d ecran 2017-04-03 a 16 45 27](https://cloud.githubusercontent.com/assets/918271/24631359/f122d622-188d-11e7-90f1-a68c7ed0971e.png)

Reported Free Space
================
![capture d ecran 2017-04-03 a 16 45 06](https://cloud.githubusercontent.com/assets/918271/24631324/da4d47c0-188d-11e7-9414-57d67416cd44.png)

**Comment by KrisBash** [comment]
@yoanisgil  I know you were redirected here from the omsagent repo, and I apologize to ask you to move it again, but the proper place for this issue is [here](https://github.com/Microsoft/SCXcore). The _provider_ that returns the file system metrics is in that SCXCore project. Also, it would be helpful to run this command and include the output relevant to this file system: 
`/opt/omi/bin/omicli ei root/scx SCX_FileSystem`

**Comment by jeffaco** [comment]
Please see [original issue](https://github.com/Microsoft/OMS-Agent-for-Linux/issues/430).

OMI is a generic framework, the problem is in the [SCXCore](https://github.com/Microsoft/SCXcore) provider.

That said, I'm actually unsure if this is an issue, you might be misunderstanding the results. I'll respond on the OMS-Agent-for-Linux issue list.

**Comment by yoanisgil** [comment]
This can be closed. Please see https://github.com/Microsoft/OMS-Agent-for-Linux/issues/430 for further information.
