### ISSUE TITLE
Add binary backward compatibility tests to test suite

### ISSUE THREAD

**Issue by palladia** [Microsoft/omi#489]
With omi-1.4.0, a binary-protocol incompatibility was introduced in libmi.so.  This caused a number of customer issues.

Going forward, we need to add additional tests to make sure compatibility between client and server/engine between releases.

**Comment by palladia** [comment]
Jumping, you can close this once new tests are added.

**Comment by JumpingYang001** [comment]
ok, we will do it, thanks.

**Comment by JumpingYang001** [comment]
Since Feb 15th-21st,2018 is Chinese Spring Festival, the tests will be automated and ready before Feb 28th, 2018, thanks.
The tests will like following:
Old omi: 1.4.2-1
New omi : next release version

**Steps:**
1.      Install new OMI
2.      Make sure omicli command works:  “/opt/omi/bin/omicli id”
3.      Create two directories, let’s call them TMP_DIR_1, and TMP_DIR_2
4.      Move libmi.so from new OMI directory to TMP_DIR_1: “mv /opt/omi/lib/libmi.so $TMP_DIR_1”
5.      Omicli command should not work (because it can’t find libmi.so).
6.      Stop omiserver:  “/opt/omi/bin/service_control stop”
7.      Start omiserver manually:  “LD_LIBRARY_PATH=$TMP_DIR_1 /opt/omi/bin/omiserver”
8.      Omicli command should work again:  “LD_LIBRARY_PATH=$TMP_DIR_1 /opt/omi/bin/omicli id”
9.      Copy old libmi.so from previous release to $TMP_DIR_2
10.     Run omicli with old library:  “LD_LIBRARY_PATH=$TMP_DIR_2 /opt/omi/bin/omicli id”.  This should work if backward compatibility is maintained.
11.     Run additional binary protocol tests
12.     Stop server and revert /opt/omi/lib/libmi.so.

**Comment by JumpingYang001** [comment]
Automated and ready now, close this issue, thanks.
